---
- name: provision new azure host
  hosts: localhost
  connection: local
  vars:
    azure_virtual_network: vnet
    azure_subnet: subnet
    azure_virtual_machine: win-vm
    azure_virtual_machine_nic: nic
    azure_vm_OS_image: 2019-Datacenter
    azure_vm_SKU: Standard_DS1_v2
    azure_vm_username: azureuser
    azure_resource_group: myResourceGroup
  vars_prompt:
    - name: azure_vm_password
      prompt: "Enter local administrator password"

  tasks:
  - name: create Azure resource group  ## リソース グループを作成する
    azure_rm_resourcegroup:
      name: '{{azure_resource_group}}'
      location: japaneast
      state: present

  - name: create Azure virtual network in resource group ## 仮想ネットワークとサブネットの作成
    azure_rm_virtualnetwork:
      name: '{{azure_virtual_network}}'
      resource_group: '{{azure_resource_group}}'
      address_prefixes_cidr:
      - 10.0.0.0/16
      state: present
  
  - name: create Azure subnet in virtualnetwork ## 仮想ネットワークとサブネットの作成
    azure_rm_subnet:
      name: '{{azure_subnet}}'
      state: present
      virtual_network_name: '{{azure_virtual_network}}'
      resource_group: '{{azure_resource_group}}'
      address_prefix_cidr: 10.0.1.0/24

  - name: Create public IP address ## パブリック IP アドレスの作成
    azure_rm_publicipaddress:
      resource_group: '{{azure_resource_group}}'
      allocation_method: Static
      name: pip
    register: output_ip_address

  - name: Output public IP
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}"

  - name: Create Network Security Group ## NSG の作成
    azure_rm_securitygroup:
      resource_group: '{{azure_resource_group}}'
      name: networkSecurityGroup
      rules:
        - name: 'allow_rdp'
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound
        - name: 'allow_web_traffic'
          protocol: Tcp
          destination_port_range:
            - 80
            - 443
          access: Allow
          priority: 1002
          direction: Inbound
        - name: 'allow_powershell_remoting'
          protocol: Tcp
          destination_port_range: 
            - 5985
            - 5986
          access: Allow
          priority: 1003
          direction: Inbound

  - name: Create a network interface ## NIC の作成
    azure_rm_networkinterface:
      name: '{{azure_virtual_machine_nic}}'
      resource_group: '{{azure_resource_group}}'
      virtual_network: '{{azure_virtual_network}}'
      subnet_name: '{{azure_subnet}}'
      security_group: networkSecurityGroup
      ip_configurations:
        - name: default
          public_ip_address_name: pip
          primary: True
        
  - name: provision new Azure virtual host ## 仮想マシンの作成
    azure_rm_virtualmachine:
      resource_group: '{{azure_resource_group}}'
      name: '{{azure_virtual_machine}}'
      vm_size: '{{azure_vm_SKU}}'
      admin_username: '{{azure_vm_username}}'
      admin_password: '{{azure_vm_password}}'
      network_interfaces: '{{azure_virtual_machine_nic}}'
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '{{azure_vm_OS_image}}'
        version: latest
      state: present

  - name: Create VM script extension to enable HTTPS WinRM listener ## WinRM リスナーを構成する
    azure_rm_virtualmachineextension:
      name: winrm-extension
      resource_group: '{{azure_resource_group}}'
      virtual_machine_name: '{{azure_virtual_machine}}'
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
      auto_upgrade_minor_version: true

  - name: wait for the WinRM port to come online ## WinRM 接続を待機する
    wait_for:
      port: 5986
      host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
      timeout: 600
